# Generated by Django 5.0.2 on 2024-04-04 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralModel",
            fields=[
                (
                    "field_name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("data_type", models.CharField(max_length=64)),
                ("aggregation_operations", models.CharField(max_length=64)),
                ("description", models.TextField()),
            ],
            options={"db_table": "general_model",},
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("grouping_type", models.CharField(max_length=255)),
                ("formula", models.JSONField(blank=True, null=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "metric_table",},
        ),
        migrations.CreateModel(
            name="Blockchain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("blockchain", models.CharField(max_length=255)),
                ("sub_chain", models.CharField(max_length=255)),
                ("original", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "blockchain_table",
                "unique_together": {("blockchain", "sub_chain")},
            },
        ),
        migrations.CreateModel(
            name="ChainMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "blockchain",
                    models.ForeignKey(
                        db_column="blockchain_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="app.blockchain",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        db_column="metric_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.metric",
                    ),
                ),
            ],
            options={
                "db_table": "chain_metric",
                "unique_together": {("blockchain", "metric")},
            },
        ),
        migrations.CreateModel(
            name="MetricsData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("blockchain", models.CharField(max_length=255)),
                ("sub_chain", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_data",
                        to="app.metric",
                    ),
                ),
            ],
            options={
                "db_table": "metrics_data",
                "unique_together": {("date", "blockchain", "sub_chain", "metric")},
            },
        ),
    ]
